### ISSUE TITLE
AbstractCategoryDocument ParentId not needed

### ISSUE THREAD

**Issue by trylika** [ongr-io/ContentBundle#36]
In this document, there is ParentId field, it shouldn't be here, DocumentInterface already has Parent field

**Comment by GrandLTU** [comment]
After looking at this issue i believe that parent field from `DocumentInterface` is used by ES with functionality not needed for catagories.

**Comment by trylika** [comment]
i disagree, @saimaz what do you think? do we really need parent and parentid fields in Category document?

**Comment by GrandLTU** [comment]
Probably i should have commented closing reason.
I discussed with saimaz this parent/child relationship is not needed for categories only id is needed.

**Comment by trylika** [comment]
Can we at least name it differently? because it's absolutely confusing to have parent and parentid fields in the same object, which have totally different uses.

Also, in parent, we can also store only id of document.

**Comment by GrandLTU** [comment]
What name you would suggest then?

But it does more than just storing parent id.

**Comment by saimaz** [comment]
IMO the `parentId` name is correct one, it means exactly how is named. It points to some id field. `parent` also name should be good since it points to parent object.
